### ISSUE TITLE
feat: passwords

### ISSUE THREAD

**Issue by bsaurusrex** [benjamin-awd/StatementSensei#10]
Would it be possible to inject pdf password options from a secrets file or env?

**Comment by benjamin-awd** [comment]
Currently, you can either store passwords in an environment variable as a string

```sh
export PDF_PASSWORDS='["pass123", "otherpw123"]'
```

or otherwise store them in an .env file in the project root:

```sh
echo 'PDF_PASSWORDS=["foo"]' > .env
```

**Comment by bsaurusrex** [comment]
Excellent.  Maybe you could add to the docker hub documentation for docker env?

**Comment by benjamin-awd** [comment]
Done! Added a note in the README and Docker Hub.
