### ISSUE TITLE
proxy config

### ISSUE THREAD

**Issue by bsaurusrex** [benjamin-awd/StatementSensei#17]
Is there an env to pass in an allowed proxy or hostname? I am trying to put this behind nginx but the content doesnt load.

**Comment by benjamin-awd** [comment]
Currently no, the host always defaults to localhost:8501 -- I'm not too familiar with nginx but you'll probably need to set up some kind of reverse proxy

Have you tried this? https://discuss.streamlit.io/t/deploy-streamlit-with-nginx-docker/52907/2

**Comment by bsaurusrex** [comment]
I found the change required.  In entrypoint.py, this needs to be my FQDN on my proxy.

"--browser.serverAddress=localhost",

Can I pass browser.serverAddress=test.example.com into the docker environment variable?

If this works, it would be good to add it to the readme.

**Comment by benjamin-awd** [comment]
Let me know if this works for you:
```
docker run -e BROWSER_SERVER_ADDRESS=test.example.com benjaminawd/statementsensei:0.7.3-rc.1
```

via PR: https://github.com/benjamin-awd/StatementSensei/pull/18/files

**Comment by bsaurusrex** [comment]
Working! Thank you.
