### ISSUE TITLE
feat: amount inversion

### ISSUE THREAD

**Issue by bsaurusrex** [benjamin-awd/StatementSensei#19]
Is it possible to have an docker env to invert the output $ amount? I find that both consolidated and credit card for ocbc/dbs both output the debit/credits opposite to what my downstream system is expecting.  Not a huge burden to manually invert it, more of a quality of life request.

**Comment by benjamin-awd** [comment]
Hmm I was thinking about adding an option to support double-entry accounting:

so something like a config setting (exposed as a env var/toggle) that would transform this:
```
| Date       | Description                    | Amount | Bank        |
| ---------- | ------------------------------ | ------ | ----------- |
| 2023-07-06 | URBAN TRANSIT CO. SINGAPORE SG | -2.40  | ExampleBank |
| 2023-07-18 | CASH REBATE                    | 1.38   | ExampleBank |
```

to this:
```
| Date       | Description                    | Debit | Credit | Bank        |
| ---------- | ------------------------------ | ----- | ------ | ----------- |
| 2023-07-06 | URBAN TRANSIT CO. SINGAPORE SG | 2.40  | 0      | ExampleBank |
| 2023-07-18 | CASH REBATE                    | 0     | 1.38   | ExampleBank |
```

Would that be helpful for your usecase? Downstream you could then invert by switching the debit or credit columns.

**Comment by bsaurusrex** [comment]
That option may work well for firefly iii data importer.

For my use case, it's just exporting to excel. for this, I just need
negatives into positives, positives into negatives to cut down on the
inversion step.

But if in the long run you want to do double-entry, focus on that as it's
more standardized.
