### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by shah-smit** [benjamin-awd/StatementSensei#22]
Hi Ben,

Awesome Library, however I am currently facing issue when running the docker on my machine (M2 Mac 2023),

```
(base)  ~ docker pull benjaminawd/statementsensei
Using default tag: latest
latest: Pulling from benjaminawd/statementsensei

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview benjaminawd/statementsensei
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by shah-smit** [comment]
Also, when trying to setup locally,

ModuleNotFoundError: No module named 'monopoly'

**Comment by benjamin-awd** [comment]
I've added support for arm64 machines, should work now! Also updated the README with more specific information on how to run it as a standalone container.
