### ISSUE TITLE
Unable to parse DBS multiplier account statements

### ISSUE THREAD

**Issue by shah-smit** [benjamin-awd/StatementSensei#23]
`Deposit Accounts Statement Multiplier.pdf -- SafetyCheckError: Total amount 107.71 cannot be found in credit statement`

**Comment by benjamin-awd** [comment]
Hey @shah-smit, does the format of your bank statement look like this?
![image](https://github.com/user-attachments/assets/98d663a2-f03e-422a-991f-e04f271df1cd)

Otherwise, does your statement contain dates like `01/2024`? (meaning that your statement has a mixture of MM/YYYY and DD/MM/YYY dates)

**Comment by shah-smit** [comment]
Hi @benjamin-awd , I think because my multiplier account (is also multi currency account) i might be the reason, i was trying to debug that.. to find out. let me check on this aspect as well.

**Comment by benjamin-awd** [comment]
If you're using the CLI, you can use `--nosafe`  to ignore the safety check which should make it easier to find which transactions are missing

Otherwise the Streamlit app raises a warning but still shows all the transactions it managed to catch.

**Comment by benjamin-awd** [comment]
Hm this looks similar to a DBS Savings account statement, but appears to have some slight differences that might be throwing off the parser

![Screenshot 2024-10-07 231940](https://github.com/user-attachments/assets/e060d388-894b-42f8-bf34-77e2e2ea6f4f)
