### ISSUE TITLE
DBS consolidated old statements not getting parsed

### ISSUE THREAD

**Issue by xRahul** [benjamin-awd/StatementSensei#25]
Old statement like:
![Screenshot 2024-10-07 214932](https://github.com/user-attachments/assets/e06bde62-654c-4311-bf4b-a01c4588bebf)

Is it possible to get some idea on how to add more types of statements here? I can add it myself, just need some idea on how to test & debug things

**Comment by benjamin-awd** [comment]
Hey @xRahul, a good starting point would be here: https://github.com/benjamin-awd/monopoly/blob/41afd2e0ebbfe0aee0ff7cedc5d6bd58de6ee6a6/src/monopoly/banks/dbs/dbs.py
